### ISSUE TITLE
Red line below "Undo" text

### ISSUE THREAD

**Issue by peah90** [soarcn/UndoBar#45]
Hello,

if Undobar is called the second time on a device with Android 5 it shows a red line below the "Undo" text. Any idea where this is coming from? First time it shows the Undobar without a red line.

![redline](https://cloud.githubusercontent.com/assets/4435255/5183814/b5858c9e-74b2-11e4-9b90-49cf057ca8b9.png)

**Comment by legarspol** [comment]
What to you call the "new version" ?
I just tried with the aar using and maven, with a clone of that library, still have the problem :-/
Didn't found any references to that red line in the code...

**Comment by soarcn** [comment]
@legarspol Can you try it with sample application and using kitkat style?

**Comment by peah90** [comment]
@legarspol Version 1.7.1 fixed the issue for us.
http://mvnrepository.com/artifact/com.cocosw/undobar/1.7.1

**Comment by legarspol** [comment]
Well this is the version I'm using...
The demo app using material also display me the red line.
Kitkat style work fine on the demo.

**Comment by soarcn** [comment]
@legarspol  I don't have a device to reproduce this defect, so please help to verify where is the issue.

As kitkat style works fine, then it must be something wrong in style.xml. Please clone the project, and try to modify the UndoBarButtonMaterial in styles.xml in line 153. You can delete or change every attribuite to see when the red line will disappear, sounds not a hard work right?

**Comment by peah90** [comment]
@legarspol I am not sure if this fixes the issue, but: If you are using AppCompat, make sure that you "extend" from AppCompats Theme and not the default Android one.

```
    <style name="MaterialTheme" parent="Theme.AppCompat.Light">
        <item name="undoBarStyle">@style/UndoBarMaterialStyle</item>
    </style>
```

**Comment by legarspol** [comment]
I really don't know what to say... --'
First this bug take some time to shows up. I can have a normal undo text and suddenly it will display the redline after X time he didn't.
I've been searching the style code, there is nothing which may change from one call to an other. Maybe is it a bad call to inflat with different parent ? 

On my android system the spellchecking underline text with typo with the exact same redline.   
is there a way that button is considered as an EditText ?

This bug has been shown on a 
- Xiaomi mi3 4.4.4
- Nexus 5     5.0.2
- Nexus 7 (second gen) 5.0.1
 Which are all the devices I tried it on.

Right now I cannot reproduce the bug which doesn't help me to play with the style settings...

**Comment by soarcn** [comment]
I doubt it would related to spellchecking, or this issue could reproduce steadily. But you can try the attribution android:inputType="textNoSuggestions" 

Because you said kikkat style works fine, you can also consider remove capitalize attribution.

Let's see
