### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Sasure** [soarcn/UndoBar#51]
I want to hide the undobar by myself,what should I do?

**Comment by soarcn** [comment]
You can use clear();

**Comment by Sasure** [comment]
可是直接用clear()相当于撤销全部操作，我已经把原本是Runnable的run()的代码独立成一个public函数了，这样就可以自己删除了。我还有一个问题，在您的Sample中的snakBar Activity里，您先在onCreate()里实例化一个UndoBarController.UndoBar对象，可是似乎没多大用处，因为响应ListView单击事件时您又直接实例化新的UndoBarController.UndoBar对象

**Comment by Sasure** [comment]
还有我将library加入我的项目出现这问题Error:Could not find property 'COMPILE_SDK_VERSION' on project，能否给个指点？

**Comment by soarcn** [comment]
Error:Could not find property 'COMPILE_SDK_VERSION'  下载api 21 sdk 或者修改gradle的compile sdk到你有的sdk版本都可以

Undobar对象是builder, 你可以任意实例化, view本身只有一个. oncreate里面那个是方便给onsavestate用的. 你也可以在ontemclick用,因为是不同版本里面增加的功能,没有统一

目前没有做针对某个message的hide接口,我没有发现具体的用例需要.你不妨描述下你的情况为什么要手动隐藏

**Comment by Sasure** [comment]
我要删除某个内容，然后会出现undobar，这时如果onPouse()被调用，就直接执行刚刚操作，而不是用clean()撤销全部操作

**Comment by soarcn** [comment]
这个就是clean的作用啊. clean并不是撤销,只是一个事件,你直接在onClean里面挨个执行操作即可.        void onClear(@NonNull Parcelable[] token);
