### ISSUE TITLE
Compile error with support-v7 22.1

### ISSUE THREAD

**Issue by AndrewNeo** [soarcn/UndoBar#53]
When I try to compile with the new v7 support library, I get the following error:

    Error: Attribute "buttonStyle" has already been defined

I do not get this error with 22.0. I assume this caused by the definition in attrs.xml conflicting with one introduced in the new support library version.

**Comment by iontech** [comment]
I second this.

@soarcn :eyes: on this please.

**Comment by DDeg** [comment]
Had same issue with buttonStyle attribute.

**Comment by soarcn** [comment]
well, I guess this is another attribute conflict issue. I don't have stable internet access this week, and will fix this next week

**Comment by yarian** [comment]
@soarcn What do you think about just prefixing all attributes with something library-specific? It ensures this will never happen again. Because it's not just about things like the support library breaking things but also about not polluting the attribute namespace.

**Comment by soarcn** [comment]
@yarian Yes, that's how I will fix this

**Comment by yarian** [comment]
@soarcn Awesome. Thanks!

**Comment by muddin1** [comment]
Works well @soarcn

**Comment by iontech** [comment]
Works well @soarcn, :bow:
