### ISSUE TITLE
Attribute "buttonStyle" already define error on support 23.0.2

### ISSUE THREAD

**Issue by psohm** [soarcn/UndoBar#56]
I have a similar issue of #53 but with support 23.0.2

`Attribute "buttonStyle" has already been defined`

It points me on a generated values.xml

`<declare-styleable name="Undobar"><attr format="reference" name="undoBarStyle"/><attr format="reference" name="inAnimation"/><attr format="reference" name="outAnimation"/><attr format="reference" name="containerStyle"/><attr format="reference" name="messageStyle"/><attr format="reference" name="**buttonStyle**"/><attr format="reference" name="dividerStyle"/></declare-styleable>`

I used : 

`compile 'com.cocosw:undobar:1.+@aar'`

**Comment by soarcn** [comment]
This should be fixed long time ago, can you try 
compile 'com.cocosw:undobar:1.8.1@aar'
